from general import about, index, search, typeahead, watched_popular,\
watched_language_popular
from social_auth import error, logout, authed_logout
from github import anonymous_github_user, github,\
github_repo, github_repo_unwatch, github_repo_watch, github_username,\
github_username_category_watched, github_username_category_watched_refresh,\
github_username_category_watched_save,\
github_username_category_watched_update, github_username_watched,\
github_username_watched_refresh, github_username_watched_save,\
github_username_watched_update, github_watched_popular,\
github_watched_language_popular
from bitbucket import bitbucket, bitbucket_repo,\
bitbucket_username, bitbucket_username_category_owned,\
bitbucket_username_category_watched,\
bitbucket_username_category_watched_refresh,\
bitbucket_username_category_watched_save, bitbucket_username_owned,\
bitbucket_username_watched, bitbucket_username_watched_refresh,\
bitbucket_username_watched_save, bitbucket_username_watched_update,\
bitbucket_username_owned_update, bitbucket_username_category_owned_update,\
bitbucket_username_category_watched_update, bitbucket_watched_popular,\
bitbucket_watched_language_popular
from authed import authed, category_owned, category_watched,\
owned, watched
